### ISSUE TITLE
compatible with v4?

### ISSUE THREAD

**Issue by sidescraper** [marmelab/ra-richtext-tiptap#2]
I think this component is not compatible with react-admin v4 yet. Can this be changed?

**Comment by fzaninotto** [comment]
TipTap is now the default rich text editor in react-admin v4. This package has been ported into ra-input-rich-text, and will therefore not be updated for v4.

**Comment by sidescraper** [comment]
ra-rich text-tiptap is listed on Third-Party Components. Has confused me. :-)
https://marmelab.com/react-admin/Inputs.html#third-party-components

**Comment by fzaninotto** [comment]
Good catch! We need to update that part of the doc.
